# vim: sw=2 ts=2 ai expandtab
---

- name: Check AWS Images for pricing
  hosts: all
  connection: local
  gather_facts: false
  become: false
  vars:
    GoodInstances:
      - RunInstances
      - RunInstances:00g0
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - debug:
        var: myvars
      when: 
        - debug is defined
        - debug
      vars:
        myvars: "{{ hostvars[inventory_hostname] }}"

    - name: ensure ami usage
      assert:
        that:
          - usage_operation is defined
          - usage_operation in GoodInstances
